### ISSUE TITLE
[OUI] Revamp developer guide

### ISSUE THREAD

**Issue by BSFishy** [opensearch-project/oui#117]
**Is your feature request related to a problem? Please describe.**

Currently, the [OUI Developer Guide](https://github.com/opensearch-project/oui/blob/d807a942f0343305eb3b2e7b65d6d5c99bba0d21/DEVELOPER_GUIDE.md) simply just links to some EUI developer guides, which outline consuming EUI, rather than working on it.

**Describe the solution you'd like**

I think [a developer guide like OpenSearch Dashboards'](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/fe4b8607b248fa379ce49ac46f2879b93771955c/DEVELOPER_GUIDE.md) would be ideal. We need a few sections about things like:
 * Common commands used during development
    * `yarn start`
    * `yarn lint`
    * `yarn test-unit`
    * `yarn build`
 * General project-related things, like file names
 * Writing HTML in OUI and some nuances with that
 * Using Typescript vs Javascript
    * Prefer Typescript over Javascript
    * Prefer modern Typescript
    * Interop between Typescript and Javascript
 * Writing SCSS in OUI and some nuances with that
    * Variable system
    * Themes
 * Writing good components

We definitely need to do some research into all that should go into the developer guide, but I just wanted to kick of the discussion for now, and start tracking the issue.

**Describe alternatives you've considered**

We could write a new developer guide, similar to EUI's (which will need to happen anyway, as we're removing all EUI references), where we explain how to use OUI from a client's perspective, however we already have the [Consuming wiki page](https://github.com/opensearch-project/oui/blob/d807a942f0343305eb3b2e7b65d6d5c99bba0d21/wiki/consuming.md), that outlines how to use OUI.

**Comment by KrooshalUX** [comment]
This is tracked in the developer experience project.

**Comment by KrooshalUX** [comment]
I would like to propose that we take this a level higher and use this thread to discuss what the developer experience should be, and not just about the markdown file. @BSFishy  @kaddy645  @bandinib-amzn  @ashwin-pc  @joshuarrrr - Do any of you have examples of "great" developer experiences? I have seen sample projects be added to these kinds of documents, is that something we would want to pursue eventually?

**Comment by ashwin-pc** [comment]
The developer guide for a design system is quite different from other developer guides imo. It need not be as complicated because it meant for users who want to contribute back to the design system which is usually rare and targeted. A markdown file(s) in the project should be enough here since the information the contributor is usually looking for is one of:
- How to setup the repo and run it
- How to add a change
- How to write a test
- Show to add it to the demo catalog
- How to write examples 
- etc

Its not for example as complex as the developer guide for dashboards which is meant for a wider audience of users who want to extend the functionality of Dashboards using its extension points and API.

To make the dev guide more accessible and readable, we can add a page to the OUI doc site if necessary, but I wouldnt complicate much more than that.
