### ISSUE TITLE
[BUG] OuiSplitButton still displays dropdown when no options available

### ISSUE THREAD

**Issue by pjfitzgibbons** [opensearch-project/oui#1208]
**Describe the bug**

When options is blank-array, or options is not present at all,  the "dropdown" side of SplitButton is still displayed, and when clicked an empty Popover is rendered.

**To Reproduce**
1. Use this TSX :
```
<OuiSplitButton >Test</OuiSplitButton>
```
2. See dropdown button
3. Click dropdown button
4. See empty Popver (2-pixel line under dropdown)

**Expected behavior**
No dropdown button, no popover

**Comment by AMoo-Miki** [comment]
While I see where you are coming from, I wouldn't categorize this as a bug because this is how an empty native `<select />` elements works too: it shows a minimal empty. Additionally, being primitive components, it is the consumer who should make sure the component is used correctly.

Thanks for raising a PR but I don't believe this is the component or the library's problem to solve. I will let others chime in as well before deciding how to move ahead.

**Comment by ashwin-pc** [comment]
My personal opinion is that a design system is supposed to abstract away the complexity of managing the UI for a developer. @AMoo-Miki what you're proposing puts the responsibility back on the developer to handle the case where there are no alternate actions. While this is simple enough to do, it goes against why we use UI libraries in the first place. The more heavy lifting the UI library can do for you, the less the developer needs to think when they use the library and the less chances there are for inconsistent patterns to show up.

**Comment by AMoo-Miki** [comment]
I love making people's lives easier and I love cohesion.
