### ISSUE TITLE
[Spike][Docs] OUI `latest` mechanism for GitHub Pages

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/oui#123]
GitHub pages can be used for versioning and hosting the docs for OUI but one mechanism that is missing is having the `latest` point to the latest and greatest version of docs.

Requirements:
* Are redirects to `latest` possible for free via GitHub pages?

**Comment by BSFishy** [comment]
From what I can tell, the entire docs site is compiled and bundled into a combination of an `index.html` page and a `bundle.min.js` file, which passes all of the routing to `react-router`.

A quick, messy solution could be to have a `gh-pages` branch, then have folders for each version with the site built for that version. Then when we release a new version, we create a new folder for that version, and make a folder called `latest` symlink to that folder.

I.e. something like

```
/
├─ 1.0.0/
│  ├─ index.html
│  ├─ bundle.min.js
│  ├─ ...
├─ 2.0.0/
│  ├─ index.html
│  ├─ bundle.min.js
│  ├─ ...
├─ latest/ -> 2.0.0/
```

Each build is already ~50MiB, so that branch could balloon up in size really quick.

**Comment by KrooshalUX** [comment]
Given the latest agreement to use the pipeline and not move forward with GitHub pages, can we close this @BSFishy ?

**Comment by BSFishy** [comment]
Yes, we can close this. We will be using our CDK pipeline going forward.
