### ISSUE TITLE
(OUI Docs) Modal

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#176]
Tab: Examples
Section: Loading and disabling confirm button > Show loading confirm modal
- [x] After you type "delete" and click "Delete button" you are shown a message that reads "SHAME ON YOU". Remove "Shame on you" from appearing (for clarity this means do not have any follow up message show at all, not just the copy removal)

**Comment by kgcreative** [comment]
So this triggers a "Delete with friction" modal, with "Delete the OUI repo?", and when you delete it, it gives the "Shame on you!" message, which seems like an attempt for cheeky humor. Should we change the popup prompt as well to say something like "Delete the selected resource?", followed by a "resource successfully deleted" toast instead of the additional confirmation message?

**Comment by KrooshalUX** [comment]
I was going to originally prescribe a toast be added but to keep focus on the demo of modal, I went without it. Happy to bring it back; was worried about adding complexity until we wrote guidance around modals being followed by toasts (which accounts for most verification use cases but I wanted to consider other possible cases as well).
