### ISSUE TITLE
(OUI Docs) Tour

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#276]
- [x] change "beta" to "experimental" badge from header
Section: Standalone steps
- [x] Change "Enter an ES SQL query" to "Enter an SQL query"
- [x] In both the UI and OUICopy component, change "SELECT email FROM "kibana_sample_data_ecommerce" to "opensearch_dashboards_sample_data_ecommerce"

Section: Managed state with the useOuiTour custom hook
- [x] Change "Enter an ES SQL query" to "Enter an SQL query"
- [x] In both the UI and OUICopy component, change "SELECT email FROM "kibanan_sample_data_ecommerce" to "opensearch_dashboards_sample_data_ecommerce"

Section: Managed state via OuiTour render prop component
- [x] Change "Enter an ES SQL query" to "Enter an SQL query"
- [x] In both the UI and OUICopy component, change "SELECT email FROM "kibanan_sample_data_ecommerce" to "opensearch_dashboards_sample_data_ecommerce"

**Comment by abbyhu2000** [comment]
Still using the <OuiBetaBadge> component but changing the label from "beta" to "experimental". Since all the page headers are registered through the <GuidePage> component in the routes.js file (if it is experiemental, then the isBeta will be set to true), all beta will be changed to experimental, not just the tour page. (if other page also set isBeta to true) @KrooshalUX
