### ISSUE TITLE
[Discuss] FlexBox Vs Grid

### ISSUE THREAD

**Issue by kaddy645** [opensearch-project/oui#31]
### Flex box layout : 
Was designed for layout in one dimension - either a row or a column

#### browser support
<img width="1461" alt="Screen Shot 2022-08-11 at 11 37 38 AM" src="https://user-images.githubusercontent.com/32860683/184214651-3a539fc0-446b-4632-909e-4a2f3f35d57a.png">

#### pros

- Flex can be arranged in any direction
- Flex can have its visual order reversed or rearranged.
- Items can be aligned in your container or between them.
- Support all browsers.

### Grid grid layout : 
Similar to flex being divided into flex containers and flex items, grid is also divided into grid containers and grid items.

#### browser support
<img width="1429" alt="Screen Shot 2022-08-11 at 11 38 15 AM" src="https://user-images.githubusercontent.com/32860683/184214676-bb25a4c5-d607-465d-bfbb-25b90f219f1a.png">

#### pros

- Grid tracks are created within your stylesheet.
- Reduced file sizes.
- Prototyping with CSS Grid is fast and efficient.

**Comment by ashwin-pc** [comment]
Given our userbase, I wouldnt worry too much about browser compatibility. We dont even actively test on older browsers and we already do use Grid in the application. Both Grid and FlexBox layout styles coexist together because they serve similar but different use cases. I think a grid vs flex discussion without context is useless because the answer will always be "it depends". Is there a specific problem we are trying to solve for here that needs a discussion between the two layout styles?

**Comment by kgcreative** [comment]
This actually leads me to think that the conversation we should be having is "What are the browsers we will choose to support"? and more importantly, "What are the browsers that we explicitly choose not to support" -- once we establish that, then we can choose the right implementation strategy for individual components. What that means is that some compositions may be better suited for a grid layout, and some might be better off with flex

**Comment by kavilla** [comment]
@kgcreative should we re-propose this issue to discuss CSS modernization?

**Comment by ashwin-pc** [comment]
@kgcreative @kavilla  Yeah, thats a better question. But in either case,  Flex box and Grid solve different layout problems, so choosing one over the other is being overly simplistic. Also even if we decide to be compatible with very old browsers, there are still very good reasons to use modern CSS features with useable (but not perfect) fallbacks for older browsers and not worry too much about browser compatibility as much like this.

**Comment by kgcreative** [comment]
@ashwin-pc -- My philosophy is "Let's use modern features, and accept graceful fall-backs" -- I personally would rather not rely too much on shims or polyfills, since those end up oftentimes introducing, rather than eliminating technical debt. Perhaps that's the primary agreement we should have here, and one that the community could help weighing in.

**Comment by kavilla** [comment]
@kaddy645 status of this?

**Comment by kgcreative** [comment]
@kavilla - I think we can close this. This was a good discussion, but I think the outcome is to evaluate which layout scheme makes the most sense for each component individually. Ultimately this will be abstracted away from both users and developers
