### ISSUE TITLE
Add searchable prop to SuperSelect

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/oui#51]
Currently the Datasource picker for the Drag and Drop editor in OpenSearch Dashboards is a custom built component since the `SuperSelect` prop does not provide the option to filter the options. Add a `filter` or `searchable` prop to `SuperSelect` to allow it to replace the custom Datasource picker.

![Screen Shot 2022-08-29 at 4 04 00 PM](https://user-images.githubusercontent.com/20453492/187313755-c9127c1c-3eea-4f1a-8d46-6d7d035cce6d.png)

**Comment by ashwin-pc** [comment]
@KrooshalUX  @kgcreative Have we prioritized this? Looks like this is the defacto Datasource selector for many new UI's. e.g. the Maps plugin. Have we prioritized this?

**Comment by kgcreative** [comment]
If we haven't, we should. Let's dig into this sooner rather than later

**Comment by kgcreative** [comment]
@ashwin-pc -- @KrooshalUX will respond with some thoughts that wouldn't require us to modify SuperSelect.

**Comment by KrooshalUX** [comment]
OUI offers many solutions to selecting objects and making choices. While the OUI team works to improve documentation and guidance on choosing components, my main concern is adding search prop option to `OuiSuperSelect increases the difficulty of decision making because there are already other components for drop-down like choice behavior that include search. `OuiSuperSelect` should remain reserved for use cases involving a small amount of choices. 

`OuiSuperSelect`, which is a stylized wrapper of `OuiSelect` offers a more visually pleasing experience for a drop down menu than the browser treatment. Generally, it should be utilized when asking the user to make a selection of choices, fewer than 9 options (aka "the 7 + or -2 rule").

The more appropriate choice would be to utilize `OuiSelectable` which has a searchable prop already. This UI is more suited for a long list of choices, and also offers the flexibility of limiting to allow the user to make a single or multiple choices within the menu and having options excluded when the case is appropriate.

**Comment by KrooshalUX** [comment]
@ashwin-pc  you may also want to look into OuiFilterSelectItem, which is a composed version of Selectable & Search within a pop-over. I am considering renaming this component to surface it up for use beyond Filter Group.

**Comment by KrooshalUX** [comment]
Further conversation and design review lead @ashwin-pc  and I to identify using `OuiComboBox` with single selection as the path forward vs adding search prop to SuperSelect. `OuiComboBox` has search implemented , but could use some touch ups to prevent user errors (@ashwin-pc  found that a user can type an incomplete entry without a match unlike `OuiFilterSelectItem`). 

The path forward for projects in flight would be for @ashwin-pc  to add a minimal amount of customization to the implementation of `OuiComboBox` to limit user errors while the OUI team works to tighten up this interaction and prepare the change for release in a next OUI version. That can be tracked here:https://github.com/opensearch-project/oui/issues/95

Closing this as no action will be taken on SuperSelect at this time.
