### ISSUE TITLE
[Discuss] Do we want to continue the recommendation of using `Progress` components as pseudo bar charts?

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/oui#596]
In https://oui.opensearch.org/1.0/#/display/progress#progress-for-charts, we advise that the `Progress` component can be used for simple bar charts, and it is used that way in some places (such as Discover field summaries). But it seems like a bit of a hack - if we want microcharts or sparklines, it seems like it would be better to provide those as part of the OpenSearch Dashboards visualization services, rather than repurposing a component designed for a different use case.

@KrooshalUX what do you think?

**Comment by KrooshalUX** [comment]
Not necessarily. This is an artifact from elastic charts but since the pattern is in use currently in OSD, I kept it there. 

Once we finalize the guidance for V12i, this would get removed from OUI. Nothing related to charting/vis will live in OUI, rather get moved to the OpenSearch Design System documentation website.

**Comment by KrooshalUX** [comment]
Closing as not planned for OUI - as this will become part of the OSDS repo once it is open. We will revise the OUI documentation website in [this issue](https://github.com/opensearch-project/oui/issues/631) when the OSDS guidance for V12i goes live.
