### ISSUE TITLE
[Research & Documentation] Describe doc site architecture & how to edit

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#66]
While we work towards analyzing accuracy of the current OUI 1.0 documentation based on the EUI 34.6 fork, it is important there is a shared understanding across UX & engineering of how the documentation site is structured and how we can collaborate to edit and maintain in its current form, until a potentially new platform is introduced for future versions of OUI.

**Comment by kgcreative** [comment]
At the very least, I'd like some clean documentation on how we might make a text edit to the documentation, and the process for how to review and deploy the change

**Comment by kgcreative** [comment]
@KrooshalUX  - reference this doc: https://github.com/opensearch-project/oui/blob/main/src-docs/src/views/guidelines/getting_started.md -- we will want to run through it together and find any gaps (For example, I had to install NVM in order to set a specific version of Node so that Yarn could build. And before Yarn, I had to install homebrew, so there is a level of technical expertise assumed in that doc.
