### ISSUE TITLE
Update OuiCollapsableNav > OuiCollapsableNavGroup background to use the same value as OuiPageBackgroundColor

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#904]

**Comment by joshuarrrr** [comment]
@KrooshalUX The `OuiCollapsibleNavGroup` actually takes a `background` prop which sets theme-defined backgrounds and can be `none` (default), `dark`, or `light`:

https://github.com/opensearch-project/oui/assets/1679762/c33f783a-2165-4e22-9b76-41ab35733096

I'm wondering if we can deprecate this if that's not something you want exposed to designers and builders. If we keep it as is, we'd need to define the behavior of each prop setting per theme.

**Comment by KrooshalUX** [comment]
I don't see this same interface where you see "set background" - but I have seen the "none" "dark" "light" array listed in props. So, this issue is about changing "dark" and "light" to the same value as OuiPageBackgroundColor, if that is a more explicit ask. I am not sure what happens when the background is set to "none" and the collapsible nav is undocked.

**Comment by joshuarrrr** [comment]
Here are the background definitions:
https://github.com/opensearch-project/oui/blob/f718f63ae058788b3a31d1aea6dfbee649c2275c/src/components/collapsible_nav/_variables.scss#L13-L23

Here are the color values in next_dark:
```
  "ouiCollapsibleNavGroupLightBackgroundColor": "#172430",
  "ouiCollapsibleNavGroupDarkBackgroundColor": "#0d1720",
  "ouiCollapsibleNavGroupDarkHighContrastColor": "#159d8d",
  "euiCollapsibleNavGroupLightBackgroundColor": "#172430",
  "euiCollapsibleNavGroupDarkBackgroundColor": "#0d1720",
  "euiCollapsibleNavGroupDarkHighContrastColor": "#159d8d",
```

Here are the color values in next_light:
```
  "ouiCollapsibleNavGroupLightBackgroundColor": "#f0f2f4",
  "ouiCollapsibleNavGroupDarkBackgroundColor": "#24313e",
  "ouiCollapsibleNavGroupDarkHighContrastColor": "#159d8d",
  "euiCollapsibleNavGroupLightBackgroundColor": "#f0f2f4",
  "euiCollapsibleNavGroupDarkBackgroundColor": "#24313e",
  "euiCollapsibleNavGroupDarkHighContrastColor": "#159d8d",
```

**Comment by joshuarrrr** [comment]
The OpenSearch Dashboards sidebar menu is composed of multiple collapsible nav group components, a couple of which are not commonly (or ever) used:

![Screenshot 2023-08-02 at 16-24-19 Dashboards - OpenSearch Dashboards copy](https://github.com/opensearch-project/oui/assets/1679762/37e26a7f-baab-4e5d-8cb4-6e8ea40af40c)

1. Custom Nav Link (no known usage)
2. Recently viewed
3. Categorized sections
4. Uncategorized nav links (if a plugin does not correctly provide a category when adding a nav link)
5. Docking controls

Note that groups 1. and 2. are currently visually distinguished from the rest with a different background shade. Additionally, they're not part of the same scroll container as everything else.
![Screenshot 2023-08-02 at 16-24-03 Dashboards - OpenSearch Dashboards](https://github.com/opensearch-project/oui/assets/1679762/7b255188-dcb7-41b2-b417-6df5f3c26a8a)
![Screenshot 2023-08-02 at 16-24-19 Dashboards - OpenSearch Dashboards](https://github.com/opensearch-project/oui/assets/1679762/370aba83-fe86-4ea2-a389-87b1b273a46b)
![Screenshot 2023-08-02 at 16-24-54 Dashboards - OpenSearch Dashboards](https://github.com/opensearch-project/oui/assets/1679762/e65db37c-9ece-491e-93b9-562d317d8b76)
![Screenshot 2023-08-02 at 16-25-15 Dashboards - OpenSearch Dashboards](https://github.com/opensearch-project/oui/assets/1679762/9fc3864f-d213-4b84-8122-802dea7db9fc)

While I think it's relatively safe to ignore 1. and 4., because we have no evidence of their use in the wild, I included them in the example screenshots for considering the overall component design

Taking into account all of the above, my recommended solution is to 

1. Update all `<EuiCollapsibleNavGroup>` components in OpenSearch Dashboard to use the set the `background` prop to `light` (which is already defined to use  `$ouiPageBackgroundColor` for all themes). 
2. Mark as deprecated the `dark` option for the `background` prop (because we have no examples of any usage of it)

![Screenshot 2023-08-02 at 15-12-01 Dashboards - OpenSearch Dashboards](https://github.com/opensearch-project/oui/assets/1679762/01e41d5c-013e-4d1f-93a1-6da5b6c18508)
![Screenshot 2023-08-02 at 15-12-29 Dashboards - OpenSearch Dashboards](https://github.com/opensearch-project/oui/assets/1679762/fa9d2577-b71a-4f4a-a596-cc28b56c2dd0)
![Screenshot 2023-08-02 at 15-13-24 Dashboards - OpenSearch Dashboards](https://github.com/opensearch-project/oui/assets/1679762/bc65385f-93a0-47c7-b308-013e50079fcb)
![Screenshot 2023-08-02 at 15-13-05 Dashboards - OpenSearch Dashboards](https://github.com/opensearch-project/oui/assets/1679762/86bffdc5-a23e-46f6-bf24-f7223bb76491)
![Screenshot 2023-08-02 at 15-14-03 Dashboards - OpenSearch Dashboards](https://github.com/opensearch-project/oui/assets/1679762/77aeb7cf-be80-452a-af1d-4230a187b5e3)
![Screenshot 2023-08-02 at 15-15-24 Dashboards - OpenSearch Dashboards](https://github.com/opensearch-project/oui/assets/1679762/a6cbfc0b-5b21-484f-881b-e275c8028cd3)
![Screenshot 2023-08-02 at 15-14-31 Dashboards - OpenSearch Dashboards](https://github.com/opensearch-project/oui/assets/1679762/e77aa152-675e-46d1-a4e1-9438983b3554)

The advantage is that we don't need to introduce theme-specific logic to this component that currently has none, and we retain flexibility to use the alternative background options in other context (the only other usage of `<EuiCollapsibleNavGroup>` today is in the maps plugin): https://github.com/search?q=org%3Aopensearch-project+EuiCollapsibleNavGroup+NOT+repo%3Aopensearch-project%2Foui+NOT+repo%3Aopensearch-project%2FOpenSearch-Dashboards&type=code 

The potential disadvantage is that it changes (subtly) the look of the nav menu existing themes, although we may consider that to be an improvement.

**Comment by KrooshalUX** [comment]
I don't know that I want the same visual effect to be applied to the current theme. In V7, the background color giving contrast to OuiCollapsibleNav is appropriate, whereas in Next, its less in-line with the overall look & feel change. The collapsible nav & header are meant to appear less "chrome-heavy" in the Next theme, thus matching the page background is ideal to balance the focus to the content. I don't know that the same approach works on v7. 

Can you update the screenshots to include a next dark version with the nav docked? Its hard to tell the outcome of the background apporach with it floating and on the scrim.

**Comment by joshuarrrr** [comment]
Screenshots updated.

**Comment by joshuarrrr** [comment]
See also https://github.com/opensearch-project/oui/pull/1016 - I ended up adding an additional themable override to the background of OuiCollapsibleNav for themes (like `next`) that would like to style it separately from `OuiFlyout`.
