### ISSUE TITLE
(OUI Next Theme) Discover

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#919]
_This issue to be transferred to corresponding repository_

I am working on launching new light and dark mode themes provided by [OUI component library](https://oui.opensearch.org/1.2/#/) for a target launch within 2.10. These changes support the vision expressed in [Future Vision for Dashboards](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4298.)

I have identified the following front end related issues that prevent the theme from appearing complete and potential solutions within this feature:

- [ ] In `Next` theme, `Source content` highlight appears too dark. Utilize sass variable (tbd) in favor of hard coded color value. Potentially utilize `EuiBadge` .
<img width="1020" alt="Screen Shot 2023-07-25 at 3 32 15 PM" src="https://github.com/opensearch-project/oui/assets/105819041/47d6f0e1-15ba-4690-8d4b-38f1e021e35d">

- [ ] View Surrounding Documents generates a table that utilizes colors from `Current` theme. These should be updated to dynamically match theme values. 
<img width="1280" alt="Screen Shot 2023-07-25 at 3 31 01 PM" src="https://github.com/opensearch-project/oui/assets/105819041/0caa7421-52dc-4c1b-bb41-29a4b6efa2ba">

- [ ] Visualizations utilizes colors from `Current` theme. Remove background and utilize `ouiPaletteColorBlind` for visualization colors. 
<img width="1037" alt="Screen Shot 2023-07-25 at 3 33 41 PM" src="https://github.com/opensearch-project/oui/assets/105819041/2c55b3ed-386f-4a00-b02a-161bfbaf18ee">

**Comment by joshuarrrr** [comment]
>  In Next theme, Source content highlight appears too dark. Utilize sass variable (tbd) in favor of hard coded color value. Potentially utilize EuiBadge .

This one is an easy fix. The reason it currently looks so bad is that they've set the opacity to just `.1`. It's an unnecessary use of transparency as a lazy way to further lighten the color rather than tint and shade.

> View Surrounding Documents generates a table that utilizes colors from Current theme. These should be updated to dynamically match theme values.

Given the current work to refactor this view altogether for data explorer, we should pick the lowest hanging fruit here, because this page is built and styled with the legacy KUI. So I'd likely need a full mock with the correct colors, or specific styling to target, because the component refactoring is already underway.

> Visualizations utilizes colors from Current theme. Remove background and utilize ouiPaletteColorBlind for visualization colors.

This is an ElasticCharts visualization, so we may need to update some of the chart themes.
