### ISSUE TITLE
Update ouiTextColorSubdued to use OuiTextColor as basis for transformation instead of ouiColorMediumShade

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#938]

**Comment by BSFishy** [comment]
old: `#6a717d`
new: `#343741` (same as `$ouiTextColor`)

in current light

**Comment by BSFishy** [comment]
Are we sure it should be based off of `$ouiTextColor`? Isn't the point of subdued being something that draws less attention, i.e. a more neutral tone? Assuming `$ouiTextColor` already has an adequate contrast ratio on the background, `$ouiTextColorSubdued` will be the same as `$ouiTextColor`, providing no visual distinction, which is what we see in current light

**Comment by joshuarrrr** [comment]
Ah, yeah good point. I think what we actually want is actually to `shade` `ouiTextColor`.

Here are the current computed values:

current light:
"ouiTextColor": `#343741`,
  "ouiTitleColor": `#1a1c21`,
  "ouiTextSubduedColor": `#6a717d`,
  "ouiColorDisabled": `#c2c3c6`,

current dark:
 "ouiTextColor": `#dfe5ef`,
  "ouiTitleColor": `#dfe5ef`,
  "ouiTextSubduedColor": `#7a7f89`,
  "ouiColorDisabled": `#434548`,

next light:
"ouiTextColor": `#2a3947`,
  "ouiTitleColor": `#1a2631`,
  "ouiTextSubduedColor": `#676e75`,
  "ouiColorDisabled": `#bdc3c8`,

next dark:
 "ouiTextColor": `#dfe5ef`,
  "ouiTitleColor": `#dfe5ef`,
  "ouiTextSubduedColor": `#86909a`,
  "ouiColorDisabled": `#4a515a`,

Now that I've looked at the code again, I think the only one we'd like to update is the calculation for next dark, because it has an explicit `ouiTextColor` that's not derived from the grayscale shades.

So my general idea was to apply `shade`, but also ensure sufficient contrast to `$ouiPageBackgroundColor`, which is used more frequently in `next`.

We also want to make sure that `ouiTextSubduedColor` is not shaded as much as `ouiColorDisabled`, and that we don't overdo it.

I tried a few different shade thresholds, which generated the following:

// $ouiTextSubduedColor: makeHighContrastColor($ouiColorMediumShade);
`#86909a`
// $ouiTextSubduedColor: makeHighContrastColor(shade($ouiTextColor, 50%), $ouiPageBackgroundColor);
`#888f97`
// $ouiTextSubduedColor: makeHighContrastColor(shade($ouiTextColor, 30%), $ouiPageBackgroundColor);
`#9fa6af`
$ouiTextSubduedColor: makeHighContrastColor(shade($ouiTextColor, 15%), $ouiPageBackgroundColor);
`#bfc5cf`

Personally I found the 30% to be about right (`#9fa6af`). T

![Image](https://github.com/opensearch-project/oui/assets/1679762/173105a1-023a-4227-ae17-3a3a3d28205c)

his is a good example page for seeing `ouiTextSubduedColor` against both `$ouiPageBackgroundColor` and `$ouiColorEmptyShade`:

@KrooshalUX We can fine tune the shading more, or if you'd rather just directly specify the subdued text color we can do that instead. Also, am I correct in my understanding that this only applies to next dark?
