### ISSUE TITLE
Update prepend/append background styles for form controls

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#939]
Top: Current - doesnt provide enough contrast on the two background possibilities 
Bottom: Updated with background color #293847 - a bit brighter and works on both backgrounds 
<img width="621" alt="Screenshot 2023-08-29 at 10 39 10 AM" src="https://github.com/opensearch-project/oui/assets/105819041/14ba1cea-2c60-4e4f-8dfc-4adc791899fd">

**Comment by joshuarrrr** [comment]
Note to selves - styling guidance inconsistent in OUI Docs + new background color needed for contrast on OuiPage and OuiPanel

@KrooshalUX Can you provide a screenshot example?

**Comment by joshuarrrr** [comment]
The color variable of interest here is `$ouiFormInputGroupLabelBackground`. Note that while these examples are mostly from `OuiFieldText`, that component is mostly a wrapper of `OuiFormControlLayout`, which is actually responsible for styling different types of prepended/appended content.

**Comment by joshuarrrr** [comment]
> The inconsistency can be addressed in a separate issue and needs additional investigation - here is the inconsistency I see (inconsistent backgrounds and text treatments)

Now that I've made the change, I can also explain the inconsistency, which is primarily just in the implementation of those examples. The form control elements with no background are intentionally that way because they're specified with `OuiEmptyButton`. And the difference in text sizes is because all of the non- "String" text elements are explicitly passing a `size` param to `OuiText`. So as part of the design system, we may decide we want to be a little more limiting in what we allow implementers to do, because I agree that it's not very uniform.

**Comment by KrooshalUX** [comment]
@joshuarrrr  thanks for the additional context. Ill start a new issue related to this for the future.
